import { Router } from "express";
import { z } from "zod";
import { prisma } from "../prisma.js";
import { ErrorHttp } from "../utilidades/errores.js";

export const rutasPortal = Router();
async function accesoValido(token: string) { const acceso = await prisma.accesoPortal.findUnique({ where: { token }, include: { cliente: { include: { organizacion: true } } } }); if (!acceso || !acceso.activo || (acceso.expiraEn && acceso.expiraEn < new Date())) throw new ErrorHttp(401, "El enlace del portal no es válido o venció"); await prisma.accesoPortal.update({ where: { id: acceso.id }, data: { ultimoAccesoEn: new Date() } }); return acceso; }
rutasPortal.get("/:token", async (req, res) => { const acceso = await accesoValido(req.params.token); const proyectos = await prisma.proyecto.findMany({ where: { clienteId: acceso.clienteId, ...(acceso.proyectoId && { id: acceso.proyectoId }) }, include: { hitos: { where: { visibleEnPortal: true }, orderBy: { orden: "asc" } }, archivos: { where: { visibilidad: "CLIENTE" }, orderBy: { creadoEn: "desc" } }, _count: { select: { tareas: { where: { estado: "COMPLETADA" } } } } } }); res.json({ estudio: { nombre: acceso.cliente.organizacion.nombre, logoUrl: acceso.cliente.organizacion.logoUrl, colorPrimario: acceso.cliente.organizacion.colorPrimario, colorSecundario: acceso.cliente.organizacion.colorSecundario, tipografia: acceso.cliente.organizacion.tipografia }, cliente: { nombre: acceso.cliente.nombre, empresa: acceso.cliente.empresa }, proyectos }); });
rutasPortal.get("/:token/comentarios", async (req, res) => { const acceso = await accesoValido(req.params.token); res.json(await prisma.comentario.findMany({ where: { proyecto: { clienteId: acceso.clienteId, ...(acceso.proyectoId && { id: acceso.proyectoId }) } }, include: { usuario: { select: { nombre: true, apellido: true } }, accesoPortal: { select: { nombre: true } } }, orderBy: { creadoEn: "asc" } })); });
rutasPortal.post("/:token/comentarios", async (req, res) => { const acceso = await accesoValido(req.params.token); const datos = z.object({ proyectoId: z.string().uuid(), contenido: z.string().min(1) }).parse(req.body); const proyecto = await prisma.proyecto.findFirst({ where: { id: datos.proyectoId, clienteId: acceso.clienteId, ...(acceso.proyectoId && { id: acceso.proyectoId }) } }); if (!proyecto) throw new ErrorHttp(403, "No tienes acceso a este proyecto"); res.status(201).json(await prisma.comentario.create({ data: { proyectoId: proyecto.id, accesoPortalId: acceso.id, autor: "CLIENTE", contenido: datos.contenido } })); });
