import { Router } from "express";
import { randomBytes } from "crypto";
import { z } from "zod";
import { prisma } from "../prisma.js";
import type { SolicitudAutenticada } from "../tipos.js";
import { ErrorHttp } from "../utilidades/errores.js";
import { registrarActividad } from "../utilidades/actividad.js";

export const rutasProyectos = Router();
const uuid = z.string().uuid();
const proyectoSchema = z.object({ clienteId: uuid, nombre: z.string().min(2), descripcion: z.string().optional().nullable(), estado: z.enum(["BORRADOR", "ACTIVO", "PAUSADO", "COMPLETADO", "CANCELADO"]).optional(), presupuesto: z.coerce.number().nonnegative().optional().nullable(), moneda: z.string().length(3).optional(), fechaInicio: z.coerce.date().optional().nullable(), fechaEntrega: z.coerce.date().optional().nullable() });
const tareaSchema = z.object({ titulo: z.string().min(2), descripcion: z.string().optional().nullable(), estado: z.enum(["PENDIENTE", "EN_PROGRESO", "BLOQUEADA", "COMPLETADA", "CANCELADA"]).optional(), prioridad: z.enum(["BAJA", "MEDIA", "ALTA", "URGENTE"]).optional(), orden: z.number().int().optional(), fechaVencimiento: z.coerce.date().optional().nullable(), hitoId: uuid.optional().nullable(), asignadoAId: uuid.optional().nullable() });
const hitoSchema = z.object({ titulo: z.string().min(2), descripcion: z.string().optional().nullable(), estado: z.enum(["PENDIENTE", "EN_PROGRESO", "COMPLETADO", "VENCIDO"]).optional(), orden: z.number().int().optional(), fechaObjetivo: z.coerce.date().optional().nullable(), visibleEnPortal: z.boolean().optional() });
const archivoSchema = z.object({ nombre: z.string().min(1), nombreOriginal: z.string().min(1), url: z.string().url(), tipoMime: z.string().min(1), tamanoBytes: z.number().int().nonnegative(), tipo: z.enum(["ARCHIVO", "ENTREGABLE", "IMAGEN", "DOCUMENTO"]).optional(), visibilidad: z.enum(["INTERNA", "CLIENTE"]).optional(), descripcion: z.string().optional().nullable() });
const proyectoPropio = async (id: string, organizacionId: string) => { const p = await prisma.proyecto.findFirst({ where: { id, organizacionId } }); if (!p) throw new ErrorHttp(404, "Proyecto no encontrado"); return p; };

rutasProyectos.get("/", async (req: SolicitudAutenticada, res) => res.json(await prisma.proyecto.findMany({ where: { organizacionId: req.sesion!.organizacionId, ...(typeof req.query.estado === "string" && { estado: req.query.estado as never }), ...(typeof req.query.clienteId === "string" && { clienteId: req.query.clienteId }) }, include: { cliente: { select: { id: true, nombre: true, empresa: true } }, _count: { select: { tareas: true, hitos: true } } }, orderBy: { actualizadoEn: "desc" } })));
rutasProyectos.post("/", async (req: SolicitudAutenticada, res) => {
  const datos = proyectoSchema.parse(req.body); const organizacionId = req.sesion!.organizacionId;
  if (!await prisma.cliente.findFirst({ where: { id: datos.clienteId, organizacionId } })) throw new ErrorHttp(422, "El cliente no pertenece a tu organización");
  const proyecto = await prisma.proyecto.create({ data: { ...datos, organizacionId, creadoPorId: req.sesion!.usuarioId } });
  await registrarActividad({ organizacionId, usuarioId: req.sesion!.usuarioId, entidad: "proyecto", entidadId: proyecto.id, accion: "CREAR", descripcion: `Creó el proyecto ${proyecto.nombre}` }); res.status(201).json(proyecto);
});
rutasProyectos.get("/:id", async (req: SolicitudAutenticada, res) => { const id = uuid.parse(req.params.id); await proyectoPropio(id, req.sesion!.organizacionId); res.json(await prisma.proyecto.findUnique({ where: { id }, include: { cliente: true, tareas: { orderBy: [{ orden: "asc" }, { creadoEn: "asc" }] }, hitos: { orderBy: { orden: "asc" } }, archivos: { orderBy: { creadoEn: "desc" } }, comentarios: { include: { usuario: { select: { nombre: true, apellido: true } }, accesoPortal: { select: { nombre: true, correo: true } } }, orderBy: { creadoEn: "asc" } }, accesosPortal: true } })); });
rutasProyectos.patch("/:id", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const datos = proyectoSchema.partial().parse(req.body); if (datos.clienteId && !await prisma.cliente.findFirst({ where: { id: datos.clienteId, organizacionId: p.organizacionId } })) throw new ErrorHttp(422, "El cliente no pertenece a tu organización"); res.json(await prisma.proyecto.update({ where: { id: p.id }, data: { ...datos, ...(datos.estado === "COMPLETADO" && { completadoEn: new Date() }) } })); });
rutasProyectos.delete("/:id", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); await prisma.proyecto.delete({ where: { id: p.id } }); res.status(204).end(); });

rutasProyectos.post("/:id/tareas", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const datos = tareaSchema.parse(req.body); if (datos.hitoId && !await prisma.hito.findFirst({ where: { id: datos.hitoId, proyectoId: p.id } })) throw new ErrorHttp(422, "El hito no pertenece al proyecto"); res.status(201).json(await prisma.tarea.create({ data: { ...datos, proyectoId: p.id } })); });
rutasProyectos.patch("/:id/tareas/:tareaId", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const tarea = await prisma.tarea.findFirst({ where: { id: uuid.parse(req.params.tareaId), proyectoId: p.id } }); if (!tarea) throw new ErrorHttp(404, "Tarea no encontrada"); const datos = tareaSchema.partial().parse(req.body); res.json(await prisma.tarea.update({ where: { id: tarea.id }, data: { ...datos, ...(datos.estado === "COMPLETADA" && { completadaEn: new Date() }) } })); });
rutasProyectos.delete("/:id/tareas/:tareaId", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const tarea = await prisma.tarea.findFirst({ where: { id: uuid.parse(req.params.tareaId), proyectoId: p.id } }); if (!tarea) throw new ErrorHttp(404, "Tarea no encontrada"); await prisma.tarea.delete({ where: { id: tarea.id } }); res.status(204).end(); });

rutasProyectos.post("/:id/hitos", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); res.status(201).json(await prisma.hito.create({ data: { ...hitoSchema.parse(req.body), proyectoId: p.id } })); });
rutasProyectos.patch("/:id/hitos/:hitoId", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const hito = await prisma.hito.findFirst({ where: { id: uuid.parse(req.params.hitoId), proyectoId: p.id } }); if (!hito) throw new ErrorHttp(404, "Hito no encontrado"); const datos = hitoSchema.partial().parse(req.body); res.json(await prisma.hito.update({ where: { id: hito.id }, data: { ...datos, ...(datos.estado === "COMPLETADO" && { completadoEn: new Date() }) } })); });
rutasProyectos.delete("/:id/hitos/:hitoId", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const h = await prisma.hito.findFirst({ where: { id: uuid.parse(req.params.hitoId), proyectoId: p.id } }); if (!h) throw new ErrorHttp(404, "Hito no encontrado"); await prisma.hito.delete({ where: { id: h.id } }); res.status(204).end(); });

rutasProyectos.post("/:id/archivos", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const archivo = await prisma.archivo.create({ data: { ...archivoSchema.parse(req.body), proyectoId: p.id, publicadoEn: req.body.visibilidad === "CLIENTE" ? new Date() : null } }); res.status(201).json(archivo); });
rutasProyectos.delete("/:id/archivos/:archivoId", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const a = await prisma.archivo.findFirst({ where: { id: uuid.parse(req.params.archivoId), proyectoId: p.id } }); if (!a) throw new ErrorHttp(404, "Archivo no encontrado"); await prisma.archivo.delete({ where: { id: a.id } }); res.status(204).end(); });

rutasProyectos.post("/:id/comentarios", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); res.status(201).json(await prisma.comentario.create({ data: { proyectoId: p.id, usuarioId: req.sesion!.usuarioId, autor: "FREELANCER", contenido: z.object({ contenido: z.string().min(1) }).parse(req.body).contenido } })); });
rutasProyectos.post("/:id/accesos-portal", async (req: SolicitudAutenticada, res) => { const p = await proyectoPropio(uuid.parse(req.params.id), req.sesion!.organizacionId); const datos = z.object({ nombre: z.string().optional(), correo: z.string().email().optional(), expiraEn: z.coerce.date().optional() }).parse(req.body); const acceso = await prisma.accesoPortal.create({ data: { ...datos, clienteId: p.clienteId, proyectoId: p.id, token: randomBytes(32).toString("base64url") } }); res.status(201).json({ ...acceso, urlPortal: `${process.env.URL_BASE || "http://localhost:4200"}/portal/${acceso.token}` }); });
